name: test

on: push

jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Display contents of test.txt
        run: echo "$(cat test.txt)"
